### PR TITLE
add url to stream as dedicated URL property to calendar item

### PR DESCRIPTION
**Pull request by Gummibeer**

### CODE REVIEW

**Comment by christophrumpel** [comment]
What does this change in detail? Where will this link then be added in the calendar, do you maybe have a screenshot so I can better visualize the change.

**Comment by Gummibeer** [comment]
This highly depends on the app used. The Apple calendar displays it as a link below the description. Others simply ignore it and more technical ones can use it to directly access the URL for a preview or whatever.

**Comment by Gummibeer** [comment]
Here's a screenshot of your stream yesterday. The very last link is the one by `url` property.
Bildschirmfoto 2021-08-18 um 10 18 18

**Comment by christophrumpel** [comment]
Thanks. But it is now the same as after the title. Is there any specific benefit to having it there again?

**Comment by Gummibeer** [comment]
Like said it massively depends on the App used how this property is used/displayed.
I was playing around with a client script reading the ICS and was in need of the URL as a dedicated variable. I could have done something like "get the third line" but this isn't as reliable as having it as a dedicated attribute in the ICS itself.
So it doesn't hurt but could be a quality of life improvement.

**Pull request merged**
