### PR TITLE
add calendar route

### PR DESCRIPTION
**Pull request by Gummibeer**
This PR adds a `calendar.ics` route which returns a calendar - you can add this URL to your Calendar app to get all streams in your calendar.

### CODE REVIEW

**Comment by freekmurze** [comment]
I'm thinking we could achieve the same without the need of having an extra route cfr what happend on meetup.laravel.com: https://github.com/spatie/meetup.laravel.com/blob/cf773392340eaf5160a87ad8ccd7ee6511b20b63/resources/views/components/event-listing.blade.php#L10

**Comment by Gummibeer** [comment]
These are two different things.
This current PR adds one calendar.ics for all events including upcoming I can subscribe to.
The linked solution is an "add to calendar" link for one single event.

**Comment by christophrumpel** [comment]
I just pushed some changes to tests, so everything should work now. I will give it a look tomorrow. Thanks @Gummibeer 👍

**Comment by christophrumpel** [comment]
@Gummibeer Looks good to me. So we would only need a download button, right?

@freekmurze so it some this does not conflict with your todo to add cal downloads for specific streams, right?

**Comment by freekmurze** [comment]
Indeed, I did not look close enough to Tom's changes. Seems all good to me!

**Comment by Gummibeer** [comment]
Yes, I've not done any UI changes as I didn't know where you want that button.
In best case I would display that URL instead of only download as most apps can subscribe to calendar URLs which will automatically import new streams to the users app.

And yes - it does not conflict with the single event button Freek mentioned.

**Comment by christophrumpel** [comment]
Thanks @Gummibeer. I will take care of showing it 👍

**Comment by christophrumpel** [comment]
I added a simple download link for now but will work on a prettier solution too.

**Pull request merged**
