### PR TITLE
Use Facades for twitter implementation

### PR DESCRIPTION
**Pull request by abenerd**
Similar to the cache and session implementation this PR allows the configuration of a twitter driver via the environment, specifically the `TWITTER_DRIVER` environment variable.
The default in the `.env.example` is the `null` driver, this driver, as the name implies, does nothing, it can be called to satisfy the interface and is the default for the local environment. In the `phpunit.xml.dist` file the driver is set to `fake`, this driver puts all tweets into an array and allows to perform assertions on said tweets, still without communicating with the actual twitter api. The third driver is the `oauth` driver, which makes use of Abraham Williams `TwitterOauth` package to actually communicate with the api and send tweets, this driver should only be used in production as it will actually send tweets out to twitter.

### CODE REVIEW

**Comment by christophrumpel** [comment]
Thanks for the PR @abenerd. I've seen this approach too lately by Luke Downing. I think it's an interesting one. I still want to check about the pros and cons.

A disadvantage I see is that it is quite some more code to maintain. I can see this approach shining with more than two drivers, but with just two, I wonder if this is a bit overload. What are the advantages in your opinion?

**Comment by abenerd** [comment]
This is also indeed where I found out about this. Unfortunately this feature is undocumented.
There is a little bit of boilerplate to it that is true, but I think it is not too overwhelming, correct me if I'm wrong. I also think it might be easier to add new drivers now that the foundation has been set, at least for twitter that is. Should you for example want to add a new driver that uses the new twitter api this would be easily possible and would then be able to be set via the environment variable. One could probably also write an a / b testing driver that varies the implementations and by using the facades then there would have to be no changes at call-site.
Also as I mentioned this is an undocumented feature so it might be nice to have this here for people to find how it works in a real life application.

**Comment by christophrumpel** [comment]
I get your points, but in this case, it is too much boilerplate for me. Also, I like to prevent preparing for scenarios that might never come like a new Twitter driver. Sorry but I don't want that approach.

But we could talk about small improvements to the current solution. I think it would be nice to use a Facade for the Twitter service, as well as a "fake" method, similar to how Laravel fakes work like "Http::fake()". This way we could use the Facade in the app code but also for testing and it would be more clear in a test that we fake the Twitter client. What do you think?

**Comment by abenerd** [comment]
I see your point, I've updated the PR to just use the facade and fake it during the tests.

**Comment by christophrumpel** [comment]
Cool, I like it. Thanks a lot!

**Pull request merged**
