### PR TITLE
Add Search to Archive page

### LINKED ISSUE #53: Add search and filter by channel to archive

### PR DESCRIPTION
**Pull request by spaantje**
Hi @christophrumpel,

So this is a PR based on the code of #95.
Please review (and merge) that PR first to get a better view of the changes in this PR. 

In this PR i add the search to the Archive page. 

Let me know if you want any changes. 

Closes #53

### CODE REVIEW

**Comment by christophrumpel** [comment]
Thanks @spaantje,

can you update this PR with the main branch so we can get rid of the conflicts?
Then I can better check the rest.

**Comment by spaantje** [comment]
> Thanks @spaantje,
> 
> can you update this PR with the main branch so we can get rid of the conflicts? Then I can better check the rest.

Done :-)

**Comment by christophrumpel** [comment]
@spaantje where does this "x" come from?

CleanShot 2021-10-10 at 19 13 09@2x

**Comment by spaantje** [comment]
That's because i used the `input type="search"`

**Comment by christophrumpel** [comment]
So it comes from the browser?

**Comment by spaantje** [comment]
Correct. It can be styled (https://stackoverflow.com/a/20804207/2252078) but don't know if it's also possible to style it with Tailwind. 

If it's unwanted we can change the `type="search"` to `type="text"` ?

**Pull request merged**
