### PR TITLE
Add Streams Archive page

### PR DESCRIPTION
**Pull request by christophrumpel**
This PR adds an archive page to show past streams. (yesterday or older)

### CODE REVIEW

**Comment by christophrumpel** [comment]
Here is what is missing:

* Navigation bar for the links `Home` and `Archive` (there will be some more nav items in the future)
* Design 🪄 for an Archive-title (currently very simple)

@Larsklopstra Do you want to work on those missing parts of this PR? (and have time)

**Comment by Larsklopstra** [comment]
Sure 🙂 I'll work on it when I have some spare time

**Comment by christophrumpel** [comment]
Awesome 👍 thx

**Comment by christophrumpel** [comment]
@Larsklopstra I already worked a little on this PR and merged it. But if you find some nice, polishing the new menu and archive page header would be nice.

**Pull request merged**
